"""update appointments to use start and end times

Revision ID: c814e673d54f
Revises: 46ae9bdf4df3
Create Date: 2026-08-13 18:21:53.715152

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c814e673d54f'
down_revision: str | Sequence[str] | None = '46ae9bdf4df3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('appointment_start', sa.DateTime(), nullable=False))
    op.add_column('appointments', sa.Column('appointment_end', sa.DateTime(), nullable=False))
    op.drop_column('appointments', 'appointment_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('appointment_date', sa.DATETIME(), nullable=False))
    op.drop_column('appointments', 'appointment_end')
    op.drop_column('appointments', 'appointment_start')
    # ### end Alembic commands ###
